### ISSUE TITLE
Looping from multiple Pipes

### ISSUE THREAD

**Issue by tafiti** [usmansbk/flappy-bird#43]
Is there an implementation that can allow pipes to keep changing based on set of pipe images in the game? 

For example, there could be five pipes of different colours that keep looping during game time.

**Comment by usmansbk** [comment]
Good idea. I was planning to randomise the bird colour instead

**Comment by tafiti** [comment]
I saw how pipes could be turned into milestones in the game. Over and above the points for each pipe passed, there would be a way to say I crossed the Nigerian pipe, the Togolese bridge etc. I will try how it can be implemented.

**Comment by usmansbk** [comment]
Oh! This is actually a great idea... 💯
