### ISSUE TITLE
Screen size on Mobile phones

### ISSUE THREAD

**Issue by tafiti** [usmansbk/flappy-bird#44]
I tried playing your game on a mobile phone (Pixel 4a). The game takes relatively 60% of the screen. Is there an implementation for a full screen experience?

**Comment by usmansbk** [comment]
Yeah, this is a problem with the game engine. Not sure how to fix it yet

**Comment by tafiti** [comment]
I like its smooth experience though. The gravity rule is well implemented. Hoping the full screen implementation won't take away that.
